language: java
jdk:
  - openjdk11

branches:
  only:
    - develop
    - feature/STUDYPOT132-readme-update

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build 시 자동으로 test 수행)
script: "cd back/ && ./gradlew clean build"
